name: Deploy Sphinx documentation to Pages

on:
  push:
    branches: [main]

jobs:
  pages:
    runs-on: ubuntu-22.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    - run: pipx install poetry
    - run: poetry install --only docs
    - id: deployment
      uses: sphinx-notes/pages@v3
