name: Deploy Sphinx documentation to Pages

on:
  push:
    branches: [main]

jobs:
  pages:
    runs-on: ubuntu-20.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - name: install poetry
      run: pipx install poetry
    - uses: actions/setup-python@v5
      with:
        python-version: 3.10
    - name: install docs dependencies
      run: poetry install --only docs
    - id: deployment
      uses: sphinx-notes/pages@v3
